_target_: src.models.mnist_module.MNISTLitModule

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.06393579793317737
  weight_decay: 0.0

# scheduler:
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.1
#   patience: 10

net: "resnet18"

# compile model for faster training with pytorch 2.0
compile: true
